"""user prefs

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 07:00:51.625732

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  autogenerate renders sqlmodel.sql.sqltypes.AutoString
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prefs", sa.JSON(), server_default="{}", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("prefs")

    # ### end Alembic commands ###
