"""Tasks and their change log."""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | Sequence[str] | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("generator_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("planting_id", sa.Integer(), nullable=True),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("group", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("earliest", sa.Date(), nullable=False),
        sa.Column("ideal", sa.Date(), nullable=False),
        sa.Column("latest", sa.Date(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("completed_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["completed_by"], ["user.id"], name=op.f("fk_task_completed_by_user"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["household_id"], ["household.id"], name=op.f("fk_task_household_id_household"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["planting_id"], ["planting.id"], name=op.f("fk_task_planting_id_planting"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task")),
        sa.UniqueConstraint("household_id", "generator_key", name=op.f("uq_task_household_id")),
    )
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_household_id"), ["household_id"], unique=False)

    op.create_table(
        "taskchange",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("what", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], name=op.f("fk_taskchange_task_id_task"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taskchange")),
    )
    with op.batch_alter_table("taskchange", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_taskchange_task_id"), ["task_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskchange", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_taskchange_task_id"))

    op.drop_table("taskchange")
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_household_id"))

    op.drop_table("task")
    # ### end Alembic commands ###
