"""Site soil class: how much water the ground holds."""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: str | Sequence[str] | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(sa.Column("soil", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("soil")

    # ### end Alembic commands ###
