"""Beds on the garden plan, and plantings that sit in them."""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | Sequence[str] | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("length", sa.Float(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"], ["household.id"], name=op.f("fk_bed_household_id_household"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bed")),
    )
    with op.batch_alter_table("bed", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bed_household_id"), ["household_id"], unique=False)

    with op.batch_alter_table("planting", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bed_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_planting_bed_id"), ["bed_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_planting_bed_id_bed"), "bed", ["bed_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("planting", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_planting_bed_id_bed"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_planting_bed_id"))
        batch_op.drop_column("bed_id")

    with op.batch_alter_table("bed", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bed_household_id"))

    op.drop_table("bed")
    # ### end Alembic commands ###
