"""Cells: where in a bed a planting sits, and when it lets go."""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  autogenerate renders sqlmodel.sql.sqltypes.AutoString
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: str | Sequence[str] | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bed", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cell_cm", sa.Integer(), server_default="30", nullable=False))

    with op.batch_alter_table("planting", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cells", sa.JSON(), server_default="[]", nullable=False))
        batch_op.add_column(sa.Column("ends_on", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("planting", schema=None) as batch_op:
        batch_op.drop_column("ends_on")
        batch_op.drop_column("cells")

    with op.batch_alter_table("bed", schema=None) as batch_op:
        batch_op.drop_column("cell_cm")

    # ### end Alembic commands ###
