"""layout

Revision ID: be0e69b2bf19
Revises: 0013
Create Date: 2026-10-10 10:36:58.512363

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  autogenerate renders sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = "0014"
down_revision: str | Sequence[str] | None = "0013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bed", schema=None) as batch_op:
        batch_op.add_column(sa.Column("layout", sa.String(), server_default="", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bed", schema=None) as batch_op:
        batch_op.drop_column("layout")

    # ### end Alembic commands ###
