"""Which catalog values are still missing or only estimated? The to-do list for contributors.

    backend/.venv/bin/python scripts/coverage.py          # write docs/COVERAGE.md
    backend/.venv/bin/python scripts/coverage.py --check  # fail if docs/COVERAGE.md is out of date (CI)

Crops are scored on the fields the crop engine reads (docs/CONTRIBUTING-CATALOG.md says where each one is used).
"""

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "COVERAGE.md"

# Dotted paths into an item; the first group is "requirements", the last "params".
CROP_FIELDS = [
    "requirements.temperature.stress_min",
    "requirements.temperature.optimal",
    "requirements.temperature.lethal_min",
    "requirements.temperature.stress_max",
    "requirements.soil_temperature.germination",
    "requirements.water.kc_mid",
    "requirements.water.root_depth",
    "requirements.soil.ph",
    "params.cycle_days",
]


def fact(item: dict, path: str) -> dict | None:
    node = item
    for part in path.split("."):
        node = node.get(part) if isinstance(node, dict) else None
    return node if isinstance(node, dict) else None


def rows() -> list[tuple[str, list[str], list[str]]]:
    out = []
    for path in sorted((ROOT / "catalog" / "crops").glob("*.yaml")):
        item = yaml.safe_load(path.read_text())
        missing = [f for f in CROP_FIELDS if fact(item, f) is None]
        estimated = [f for f in CROP_FIELDS if (v := fact(item, f)) and v.get("estimate")]
        out.append((item["slug"], missing, estimated))
    return out


def render() -> str:
    data = rows()
    total = len(data) * len(CROP_FIELDS)
    gaps = sum(len(m) + len(e) for _, m, e in data)
    lines = [
        "# Catalog coverage",
        "",
        "Generated by `scripts/coverage.py`; do not edit by hand. Every gap below is a good first contribution:",
        "see [CONTRIBUTING-CATALOG.md](CONTRIBUTING-CATALOG.md).",
        "",
        f"**Crops:** {len(data)} · fields filled with a sourced value: {total - gaps} of {total}",
        "",
        "| Crop | Missing | Estimate only |",
        "|---|---|---|",
    ]
    short = lambda fs: ", ".join(f.split(".", 1)[1] for f in fs) or "none"  # noqa: E731
    lines += [f"| {slug} | {short(m)} | {short(e)} |" for slug, m, e in data]
    lines += ["", "Animals, varieties and organisms are not in the catalog yet; adding the first ones is also welcome.", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit("docs/COVERAGE.md is out of date: run scripts/coverage.py")
    else:
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(ROOT)}")
